[package]
name = "carbon_marketplace"
version = "1.0.0"
edition = "2024.beta"

[dependencies]
Sui = { local = "../sui/crates/sui-framework/packages/sui-framework" }
MoveStdlib = { local = "../sui/crates/sui-framework/packages/move-stdlib" }
Bridge = { local = "../sui/crates/sui-framework/packages/bridge" }

[addresses]
carbon_marketplace = "0x0" 